/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.agendamento.view;

import br.com.ifba.agendamento.model.Agendamento;
import br.com.ifba.agendamento.service.IServiceAgendamento;
import br.com.ifba.agendamento.service.ServiceAgendamento;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Henrique
 */
public class TelaRemarcar extends javax.swing.JFrame {

   
    private Calendar dataSelecionada;
    private Calendar horaSelecionada;

    private final IServiceAgendamento serviceAgendamento; // Certifique-se de injetar seu serviço aqui.

    public TelaRemarcar(IServiceAgendamento serviceAgendamento) {
        initComponents();
        this.serviceAgendamento = serviceAgendamento;

        jTable1.addMouseListener(new MouseAdapter() {
    @Override
    public void mouseClicked(MouseEvent e) {
        System.out.println("Clique detectado!");
        if (e.getClickCount() == 1) {
            int linhaSelecionada = jTable1.getSelectedRow();
            if (linhaSelecionada != -1) {
                dataSelecionada = (Calendar) jTable1.getValueAt(linhaSelecionada, 0);
                horaSelecionada = (Calendar) jTable1.getValueAt(linhaSelecionada, 1);
            }
        }
    }
});
    }

    private void preencherTabela() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        
    List<Agendamento> agendamentos = serviceAgendamento.getAllAgendamento();
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        SimpleDateFormat timeFormat = new SimpleDateFormat("HH:mm");

        for (Agendamento agendamento : agendamentos) {
            Calendar data = agendamento.getDataAgendamento();
            Calendar hora = agendamento.getHoraAgendamento();

            model.addRow(new Object[]{dateFormat.format(data.getTime()), timeFormat.format(hora.getTime())});
        }
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        bntConfirma = new javax.swing.JButton();
        bntSuporte = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("REMARCAÇAO");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Data", "Horario"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setText("selecione a data e hoarario disponivel");

        bntConfirma.setText("OK");
        bntConfirma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntConfirmaActionPerformed(evt);
            }
        });

        bntSuporte.setText("SUPORTE");
        bntSuporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntSuporteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(jLabel2)
                .addContainerGap(112, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(bntSuporte)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bntConfirma)
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(2, 2, 2)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bntConfirma)
                    .addComponent(bntSuporte))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntConfirmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntConfirmaActionPerformed
       if (dataSelecionada != null && horaSelecionada != null) {
            Agendamento novoAgendamento = new Agendamento();
            novoAgendamento.setDataAgendamento(dataSelecionada);
            novoAgendamento.setHoraAgendamento(horaSelecionada);

            serviceAgendamento.updateAgendamento(novoAgendamento);
             ServiceAgendamento service = new ServiceAgendamento(); // ou qualquer outra forma de criar um objeto ServiceAgendamento
                TelaRemarcar tela = new TelaRemarcar(service);
                tela.setVisible(true);
            preencherTabela();

            JOptionPane.showMessageDialog(this, "Solicitação de remarcação confirmada. Um e-mail será enviado quando o(a) psicólogo(a) confirmar, juntamente com a chave de acesso.");
        } else {
            JOptionPane.showMessageDialog(this, "Selecione uma data e hora para remarcar a consulta.");
        }
    }//GEN-LAST:event_bntConfirmaActionPerformed

    private void bntSuporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntSuporteActionPerformed
        try {
     //nao implementaro enviarParaListaDeEspera(); // Chame o método ao clicar no botão "Suporte"
             TelaEspera tela = new TelaEspera();
                tela.setVisible(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(TelaRemarcar.this, "Erro ao enviar para lista de espera: " + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
       
    }//GEN-LAST:event_bntSuporteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaRemarcar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaRemarcar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaRemarcar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaRemarcar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {            
                ServiceAgendamento service = new ServiceAgendamento(); // ou qualquer outra forma de criar um objeto ServiceAgendamento
                TelaRemarcar tela = new TelaRemarcar(service);
                tela.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntConfirma;
    private javax.swing.JButton bntSuporte;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
