# A identação do código é dividido em seção e subseções (IMPORTANTE SER CAUTELOSO com o espaçamento das sentenças)

name: flutter_application_1
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

 
  uses-material-design: true

  assets:
    - imagens/ # O projeto incorpora todas as imagens que estiver dentro da pasta "imagens"